### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by borgstrom** [NerdWalletOSS/terraformpy#44]
We should be mostly compatible, but when running `pipenv install terraformpy` with Python 3 available the install fails since this package is not marked as universal and supporting 3+.

**Comment by ss-remygreinhofer** [comment]
Running `pytest` on Python `3.7.5`, resulted in `25 failed, 4 passed, 61 warnings in 0.32s`.

Python 2 only has a few days left to live, do you have any plan to migrate to a full Python 3 solution? 

Do you need help with this effort? And do you have a plan to tackle this upgrade? I could not find any other issues or wiki page addressing this issue.
